### ISSUE TITLE
Feature: Add the possibility to ignore method parameters for PublishOperation / SubscribeOperation annotated methods

### ISSUE THREAD

**Issue by KevinD-87** [neuroglia-io/asyncapi#32]
## Description
In our implementations, we need to be able to pass a `CancellationToken` to the underlying publish SDK call, which requires an additional parameter on the method that gets annotated with the `PublishOperation` / `SubscribeOperation` attributes. This additional parameter has no value for the AsyncAPI specification, but we can't instruct the generator to ignore this parameter.

## Alternatives
I've tried annotating the parameter with the `JsonExcludeAttribute` from the `JsonSchema.Generation` package, but that can't be applied to method parameters.

## Additional info
In the generated output, the unwanted parameter (in this case 'cancellationToken') shows up as follows:
```
channels:
  item/created:
    publish:
      operationId: onItemCreated
      message:
        payload:
          type: object
          properties:
            itemCreatedEvent:
              type: object
              properties:
                id:
                  type: string
                  format: uuid
                  description: Unique identifier of the item
                  readOnly: True
              required:
              - id
            cancellationToken:
              type: object
              properties:
                isCancellationRequested:
                  type: boolean
                  readOnly: True
                canBeCanceled:
                  type: boolean
                  readOnly: True
                waitHandle:
                  type: object
                  properties:
                    handle:
                      type: object
                      deprecated: True
                    safeWaitHandle:
                      type: object
                      properties:
                        isClosed:
                          type: boolean
                          readOnly: True
                        isInvalid:
                          type: boolean
                          readOnly: True
                  readOnly: True
          required:
          - itemCreatedEvent
          - cancellationToken
```
